// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CleansingAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Ride Distance (km)"), LoadColumn(0)]
        public float Ride_Distance__km_ { get; set; }


        [ColumnName("Vehicle Type"), LoadColumn(1)]
        public string Vehicle_Type { get; set; }


        [ColumnName("Promo Value"), LoadColumn(2)]
        public float Promo_Value { get; set; }


        [ColumnName("Fare"), LoadColumn(3)]
        public float Fare { get; set; }


        [ColumnName("Paid"), LoadColumn(4)]
        public float Paid { get; set; }


        [ColumnName("Hour"), LoadColumn(5)]
        public float Hour { get; set; }


        [ColumnName("Minute"), LoadColumn(6)]
        public float Minute { get; set; }


        [ColumnName("Class"), LoadColumn(7)]
        public string Class { get; set; }


        [ColumnName("Day"), LoadColumn(8)]
        public string Day { get; set; }


        [ColumnName("Saving"), LoadColumn(9)]
        public float Saving { get; set; }


    }
}
