// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using CleansingAppML.Model;

namespace CleansingAppML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\jobs\Hikaton\Model\BusinessProfile4.csv";

        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Saving with predicted Saving from sample data...\n\n");
            Console.WriteLine($"Ride Distance (km): {sampleData.Ride_Distance__km_}");
            Console.WriteLine($"Vehicle Type: {sampleData.Vehicle_Type}");
            Console.WriteLine($"Promo Value: {sampleData.Promo_Value}");
            Console.WriteLine($"Fare: {sampleData.Fare}");
            Console.WriteLine($"Paid: {sampleData.Paid}");
            Console.WriteLine($"Hour: {sampleData.Hour}");
            Console.WriteLine($"Minute: {sampleData.Minute}");
            Console.WriteLine($"Class: {sampleData.Class}");
            Console.WriteLine($"Day: {sampleData.Day}");
            Console.WriteLine($"\n\nActual Saving: {sampleData.Saving} \nPredicted Saving: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
